# Site
repository: thomascamminady/thomascamminady.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Dr. Thomas Camminady
title: Algorithm Developer
email: bumqvy1v@duck.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  thomascamminady
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: camminady
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
googlescholar_username: kczWHoQAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: #About Me (Use this to override about section title)
# about_profile_image: images/Camminady.jpg
#about_content: | # this will include new lines to allow paragraphs
#  Write an awesome description about yourself here.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Wahoo Fitness
        sub_title: Algorithm Developer
        caption: Since March 2021
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Creation of APIs that allow the automatic monitoring of hardware and software quality metrics.
          - Time series analysis and sensor fusion for various sources of data using Python.
          - Statistical analysis of sports related data and creation of interactive dashboards for visualization.
          - Code generation for low-level hardware using Matlab.
          - Code documentation and result summaries in Confluence.
          - Sprint planning using Jira in an agile environment.
      - layout: left
        title: Steinbuch Centre for Computing, Karlsruhe Institute of Technology
        sub_title: Scientific Staff 
        caption: September 2017 - March 2021
        description: |
          - Research in the field of kinetic theory, numerical mathematics, and machine learning. This encompasses the development of new algorithms to solve transport problems (e.g., the transport equation for radiation therapy), their implementation, and their analysis.
          - Using concepts from machine learning and optimization theory, to automatically generate near-optimal sets of problem- dependent numerical parameters for the solution of advection problems.
          - I optimized the performance of research software on the HPC cluster of the Karlsruhe Institute of Technology via parameter studies and OpenMP.
          - For modules in the mathematics M.Sc. program (including Kinetic Theory and Uncertainty Quantification) and modules in the Computational Engineering Science B.Sc. program, I was a teaching assistant and substituted lectures.
      - layout: left
        title: Mathematical Center for Computational Engineering Science, RWTH Aachen University
        sub_title: Scientific Staff 
        caption: March 2015 - September 2017
        description: |
          - Research in the field of kinetic theory, numerical mathematics, and machine learning. This encompasses the development of new algorithms to solve transport problems (e.g., the transport equation for radiation therapy), their implementation, and their analysis.
          - Help with lectures in the Computational Engineering Module.
          - Presentations at international conferences.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Karlsruhe Institute of Technology
        sub_title: Ph.D. Applied Mathematics
        caption: September 2017 to March 2021
        # quote: >
          # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - Dissertation: ["Theory, models, and numerical methods for classical and non-classical transport"](https://github.com/thomascamminady/thomascamminady.github.io/raw/main/assets/CAMMINADY%20-%20Theory%2C%20models%2C%20and%20numerical%20methods%20for%20classical%20and%20non-classical%20transport.pdf)
          - Research in the field of kinetic theory, numerical mathematics, and machine learning. This encompasses the development of new algorithms to solve transport problems (e.g., the transport equation for radiation therapy), their implementation, and their analysis.
          - Using concepts from machine learning and optimization theory, to automatically generate near- optimal sets of problem-dependent numerical parameters for the solution of advection problems.
          - I optimized the performance of research software on the HPC cluster of the Karlsruhe Institute of Technology via parameter studies and OpenMP.
          - For modules in the mathematics M.Sc. program (including Kinetic Theory and Uncertainty Quantification) and modules in the Computational Engineering Science B.Sc. program, I was a teaching assistant and substituted lectures.
      - layout: left
        title: RWTH Aachen University
        sub_title: M.Sc. Computational Engineering Science
        caption: September 2013 to September 2015
        # quote: >
          # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - Thesis: ["Theory and application of numerical methods for fractional diffusion equations"](https://github.com/thomascamminady/thomascamminady.github.io/raw/main/assets/CAMMINADY%20-%20Theory%20and%20application%20of%20numerical%20methods%20for%20fractional%20diffusion%20equations.pdf)
          - Tutoring in the field of numerical mathematics and programming.
          - Research student at the Mathematical Center for Computational Engineering Science.
          - Courses on (applied) mathematics, optimization methods, and algorithmic differentiation.
      - layout: left
        title: RWTH Aachen University
        sub_title: B.Sc. Computational Engineering Science
        caption: October 2009 to September 2013

        # quote: >
          # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - Thesis: ["Improvement of the aerodynamic shape optimization by adjoint methods in an MDO process"](https://github.com/thomascamminady/thomascamminady.github.io/raw/main/assets/CAMMINADY%20-%20Improvement%20of%20the%20aerodynamic%20shape%20optimization%20by%20adjoint%20methods%20in%20an%20MDO%20process.pdf)  
          - Internship and Bachelor's thesis with EADS Cassidian, Manching, Germany.
          - Courses on (applied) mathematics, fluid mechanics, and high-performance computing.



  - title: Publications
    layout: list
    content:
      - layout: left
        title: Journal articles
#        sub_title: Ph.D. Applied Mathematics
#        caption: September 2017 to March 2021
        # quote: >
          # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - [Mathematische Grundlagen der künstlichen Intelligenz im Schulunterricht](https://link.springer.com/article/10.1007/s00591-021-00310-x),
            Sarah Schönbrodt, **TC**, and Martin Frank. Mathematische Semesterberichte, pages 1–29, 2021.
          - [Ray Effect Mitigation for the Discrete Ordinates Method Using Artificial Scattering](https://doi.org/10.1080/00295639.2020.1730665),

            Martin Frank, Jonas Kusch, **TC**, and Cory D. Hauck. Nuclear Science and Engineering, 194(11):971–988, 2020.
          - [Ray effect mitigation for the discrete ordinates method through quadrature rotation](http://www.sciencedirect.com/science/article/pii/S0021999119300415),
            **TC**, Martin Frank, Kerstin Küpper, and Jonas Kusch. Journal of Computational Physics, 382:105 – 123, 2019. 
          - [A spectral galerkin method for the fractional order diffusion and wave equation](https://link.springer.com/article/10.1007/s12572-018-0208-y),
            **TC** and Martin Frank. International Journal of Advances in Engineering Sciences and Applied Mathematics, 10(1): 90–104, 2018.
          - [A new high-order fluid solver for tokamak edge plasma transport simulations based on a magnetic-field independent discretization](https://onlinelibrary.wiley.com/doi/abs/10.1002/ctpp.201700172),
            G. Giorgiani, **TC**, H. Bufferand, G. Ciraolo, P. Ghendrih, H. Guillard, H. Heumann, B. Nkonga, F. Schwander, E. Serre, and P. Tamain. Contributions to Plasma Physics, 58(6-8):688–695, 2018.
    
      - layout: left
        title: Conference proceedings 
#        sub_title: Ph.D. Applied Mathematics
#        caption: September 2017 to March 2021
        # quote: >
          # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - [Highly uniform quadrature sets for the discrete ordinates method](https://drive.google.com/file/d/1Rppj5fyGRVlmAQeUbMwnGfuZE5KIpEIT/view),
            **TC**, Martin Frank, and Jonas Kusch. In Proc. Int. Conf. Mathematics and Computational Methods Applied to Nuclear Science and Engineering, pages 25–29, 2019. 
          - [Nonclassical particle transport in heterogeneous materials](https://www.kns.org/files/int_paper/paper/MC2017_2017_1/P061S01-12CamminadyT.pdf),
            **TC**, Martin Frank, and Edward W Larsen. In International Conference on Mathematics & Computational Methods Applied to Nuclear Science & Engineering, 2017. 
          - [The equivalence of forward and backward nonclassical particle transport theories](www.kns.org/files/int_paper/paper/MC2017_2017_1/P020S01-03LarsenE.pdf),
            Edward W Larsen, Martin Frank, and **TC**. In International Conference on Mathematics & Computational Methods Applied to Nuclear Science & Engineering, 2017.

      - layout: left
        title: Book chapters
#        sub_title: Ph.D. Applied Mathematics
#        caption: September 2017 to March 2021
        # quote: >
          # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - [Vorschlag für eine Abiturprüfungsaufgabe mit authentischem und relevantem Realitätsbezug](https://doi.org/10.1007/978-3-662-60815-9_8),
            Maike Sube, **TC**, Martin Frank, and Christina Roeckerath. Springer Berlin Heidelberg, Berlin, Heidelberg, 2020.
            URL https://doi.org/10.1007/978-3-662-60815-9_8
  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

footer_show_references: false

sass:
  sass_dir: _sass
  style: compressed

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
